/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphtheoryproject;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ArrayList;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JInternalFrame;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Nilaya
 */
public class OutputPage extends javax.swing.JFrame
{

    
    int currindex;
    ArrayList<Vertex> vertexlist;
    ArrayList< ArrayList<Edge> > subgraphlist;
    /**
     * Creates new form OutputPage
     */
    public OutputPage()
    {
        initComponents();
        
    }
    
    public OutputPage(ArrayList<Vertex> vertexlist, ArrayList< ArrayList<Edge> > subgraphlist)
    {
        
        
        this.currindex=1;
        this.vertexlist=vertexlist;
        this.subgraphlist=subgraphlist;
        
        
        initComponents();
        for(int i=1;i<subgraphlist.size();++i)
            jComboBox1.addItem(""+i);
        jButton2.setEnabled(true);
        jButton1.setEnabled(false);
        setLayout(new BorderLayout());
        this.setVisible(true);
        //SubgraphsFrame.add((Component) view);
        drawGraph();
        checkNav();
    }
    
    void drawGraph()
    {
       
        
        jPanel1.removeAll();
        Graph graph = new SingleGraph("MyGraph");
       
        
        
       
        
        ArrayList<Edge> edges=new ArrayList<>();
        edges= subgraphlist.get(currindex);
        
        
        /*for(Vertex v:vertexlist)
        {
            graph.addNode(new Integer(v.getNodeNo()).toString());
        }*/
        
        int i=0;
        System.out.println("subgraphlist size="+subgraphlist.size());
        System.out.println("edges size="+edges.size());
        
        for(Edge e:edges)
        {
            if(graph.getNode(Integer.toString(e.getV1().getNodeNo())) == null)
                graph.addNode(Integer.toString(e.getV1().getNodeNo()));
            if(graph.getNode(Integer.toString(e.getV2().getNodeNo())) == null)
                graph.addNode(Integer.toString(e.getV2().getNodeNo()));
            graph.addEdge(Integer.toString(i), Integer.toString(e.getV1().getNodeNo()),Integer.toString(e.getV2().getNodeNo()));
            i++;
        }
        
        graph.addAttribute("ui.stylesheet",styleSheet);
        graph.addAttribute("ui.antialias");
        
        
        
        for (Node node : graph) 
        {
            node.addAttribute("ui.label", node.getId());
        }
       
        
        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        View view = viewer.addDefaultView(false);
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Activate autolayout here : 
        viewer.enableAutoLayout();
       
        JInternalFrame sgf=new JInternalFrame();
        sgf.setSize(jPanel1.getSize());
        sgf.setLayout(new BorderLayout());
        
        sgf.add((Component) view, BorderLayout.CENTER);
        
        sgf.setVisible(true);
        jPanel1.add(sgf);
       
        /*graph.setStrict(false);
        graph.setAutoCreate(true);
        graph.display();*/
       
       subgrnum.setText(""+currindex+"/"+(subgraphlist.size()-1));
        
    }
   
   
    
    
    void checkNav()
    {
        if(currindex==subgraphlist.size()-1)
            jButton2.setEnabled(false);
        else
            jButton2.setEnabled(true);
        
        if(currindex==1)
            jButton1.setEnabled(false);
        else
            jButton1.setEnabled(true);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        subgrnum = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("PREVIOUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jLabel2.setText("Subgraph Number:");

        subgrnum.setText("0");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("JUMP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subgrnum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subgrnum)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        
        currindex--;
        drawGraph();
        checkNav();
        jComboBox1.setSelectedIndex(currindex-1);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

        currindex++;
        drawGraph();
        checkNav();
        jComboBox1.setSelectedIndex(currindex-1);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     currindex = Integer.parseInt((String) jComboBox1.getSelectedItem());
        drawGraph();
        checkNav();
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    protected String styleSheet =
            "node {" +
            "	fill-color: rgb(85,134,192);" +
            "}" +
            "node.marked {" +
            "	fill-color: rgb(120,198,20);" +
            "}" +
            "node {" +
            "	shape: circle;" +
            "}" +
            "node {" +
            "	size: 30px;" +
            "}" +
            "node {" +
            "	size-mode: fit;" +
            "}" +                
            "node {" +
            "	text-color: blue;" +
            "}" +
            "node {" +
            "	text-size: 25px;" +
            "}" +
            "node {" +
            "	arrow-shape: circle;" +
            "}" +
            "node {" +
            "	shadow-mode: gradient-vertical;" +
            "}" +                
            "node {" +
            "	shadow-color: yellow;" +
            "}" +
            "node {" +
            "	shadow-width: 4px;" +
            "}" +                
            "node {" +
            "	text-alignment: above ;" +
            "}" +
            "node {" +
            "	text-style: bold-italic;" +
            "}" +
            "edge {" +
            "	size: 8px;" +
            "}" +
            "edge {" +
            "	fill-color: rgb(89,178,10);" +
            "}" +               
            "edge {" +
            "	shape: blob;" +
            "}" +           
            "edge {" +
            "	arrow-shape: diamond;" +
            "}";                
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OutputPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OutputPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OutputPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OutputPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OutputPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subgrnum;
    // End of variables declaration//GEN-END:variables
}
